### ISSUE TITLE
Should we do some doctest tests?

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#108]
There's a fair amount of examples in the code and it would be ideal to make sure that those examples stay valid at all times. This can often be achieved with doctest tests (some examples may not be full, e.g. because of complex inputs, and those can be skipped).

**Comment by shantanu-gontia** [comment]
The comments in the output will need to be moved elsewhere, otherwise `doctest` wouldn't work. I tried this with the examples in the `kinematics.py` file. 
~~~~
>>> lifetime_to_width(0.001520119980246514*ns)
    4.33  # result again returned in MeV
~~~~ 
fails while
~~~~
>>> lifetime_to_width(0.001520119980246514*ns)
    4.33  # result again returned in MeV
~~~~ 
passes.

**Comment by eduardo-rodrigues** [comment]
That's right, @shantanu-gontia, thanks. There are quite a few of these to be changed, if one does go forward with doctests. This is probably a task for the medium term, once a few other bits are added to the package.

**Comment by eduardo-rodrigues** [comment]
Just for my record, I should look at `pytest --doctest-modules --ignore-glob="*__main__.py"`.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/148.
