### ISSUE TITLE
SPAN breaks dot graphs

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#124]
The addition of SPAN to the html_name breaks dot graphs. This should be optional, adjustable, or dot-friendly. Also not sure why this is uppercase.

**Comment by henryiii** [comment]
Possible solution: use unicode: https://en.wikipedia.org/wiki/Overline#Unicode

**Comment by eduardo-rodrigues** [comment]
Agreed, let's make it more friendly.
BTW, the uppercases that's because you had HTML code in uppercase and I followed that ;-). Personally I also prefer lowercase <span>, <sub>, etc.

**Comment by eduardo-rodrigues** [comment]
I got back to this, @henryiii. In the end it is simpler to use HTML special characters rather than Unicode.

**Comment by henryiii** [comment]
Did you check to verify it works with the diagrams?

**Comment by eduardo-rodrigues** [comment]
Nope, see my comment "Fixes #124 - to be checked with DecayLanguage." at the very top of the PR.

**Comment by eduardo-rodrigues** [comment]
I need to update `DecayLanguage` to try and display HTML names rather than simply the names in order to check this. Will do so asap, but not tonight.

**Comment by eduardo-rodrigues** [comment]
OK, I've done some digging and tests - a bit of a pain. To the best of my knowledge there is some limitation in using HTML in Dot record shapes, which are the ones I use to have those boxes with several particles, when every single box item can be linked to decay products. I now managed to test that I can achieve almost the same with the plaintext shape. Bottom line, my trouble is to be sorted out in `DecayLanguage`, not here.

This being said, what I'm proposing in https://github.com/scikit-hep/particle/pull/156 works and provides much shorter text, so I would go with that :-).
