### ISSUE TITLE
Add CONTRIBUTING.md/.rst

### ISSUE THREAD

**Issue by matthewfeickert** [scikit-hep/particle#131]
@henryiii @eduardo-rodrigues It would be great to have a `CONTRIBUTING` guidelines file for this project. They're quite useful for having people from outside the core developers make useful contributions that aren't a pain for the dev team to review.

**Comment by eduardo-rodrigues** [comment]
I'm not a huge fan of these as they often list trivialities or kind of impose a workflow, which is not necessarily the way everyone develops. But we can try and get something reasonable … and you will have to review that file, OK ;-)?

**Comment by matthewfeickert** [comment]
> I'm not a huge fan of these as they often list trivialities or kind of impose a workflow, which is not necessarily the way everyone develops. 

It is your project, so you and @henryiii should do as you like &mdash; this is just my suggestion. 

Though, "impos[ing[ a workflow" is a positive side effect of `CONTRIBUTING` which will automatically make it easier for the code devs to review PRs. Would you be willing to share why you view this (the workflow) as a negative?

In my mind though, the `CONTRIBUTING` is far more helpful/important to people _outside_ the core devs. Consider a young (so not me :stuck_out_tongue_winking_eye:) HEP Ph.D. student who comes across your project, thinks it is super cool, but is just getting started with collaborative coding and really doesn't know how to contribute to a project at all. Instead of them wasting time trying to figure out what you would like them to even do if they can read a `CONTRIBUTING` and then immediately move to suggested Issues and open a PR that is compliant with all the expectations you have before tagging you for review.

https://mozillascience.github.io/working-open-workshop/contributing/

> and you will have to review that file

Totally willing to do so. Though it needs to reflect what the core devs want (I'm just a drive by contributor :slightly_smiling_face:).

**Comment by eduardo-rodrigues** [comment]
Thanks a lot for the discussion and link, @matthewfeickert!
My "worry" really is that a contributions file kind of imposes to use a virtual env or alike. But I guess you can argue that it's all a matter of writing good instructions. I take your points - only fools don't change their minds, right?

We will try and come up with something, and will ping you ...

Thanks again!

**Comment by matthewfeickert** [comment]
Thanks very much for considering this suggestion! 

> My "worry" really is that a contributions file kind of imposes to use a virtual env or alike. But I guess you can argue that it's all a matter of writing good instructions. I take your points - only fools don't change their minds, right?

I think you can definitely see my development methodology bias showing in my comments (given that the `pyhf` developer docs ask for this sort of thing https://diana-hep.org/pyhf/development.html). So please know that though I may seem pushy in the comments here I always do mean them as suggestions and not demands. Also I know I can be the fool you describe above sometimes. :P

**Comment by eduardo-rodrigues** [comment]
@henryiii, I see you've been creating a CONTRIBUTING file for other Scikit-HEP packages (hist and/or aghast IIRC). Can we maybe copy that file here, once finalised? Then we close this long-standing "issue" :-).

**Comment by henryiii** [comment]
I'm currently writing a guideline for the scikit-hep.org page, and then that can be used as a basis for many of our packages. :)

**Comment by eduardo-rodrigues** [comment]
Brilliant, that's a more long-term solution!
