### ISSUE TITLE
Black formatting

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#173]
I think it would be a good idea to [format the code with Black](https://black.readthedocs.io/en/stable/). Would other devs (@eduardo-rodrigues) be fine with that?

**Comment by henryiii** [comment]
(We could possibly try using `pre-commit` git integration for it)

**Comment by eduardo-rodrigues** [comment]
I find it useful to have a common look in packages. There are many formatting tools but this seems to take a slightly different approach. Have you given it a go privately? Anywhere I can have a look at the result?

**Comment by henryiii** [comment]
I've started using it in Boost.Histogram. Black seems to be gaining traction very quickly, and it's from the Python Software Foundation. It's "Uncompromising" (very unconfigurable), but it's sort of becoming a standard and that's good for reading code quickly. I can throw together a PR so you can see what it looks like. `python -m pip install black` followed by `python -m black .` should pretty much do it, though. You can adjust a few things (like what files to include or ignore) in setup.cfg, but that's about it.

@HDembinski has been reading and formatting code with it for a little bit as a result, he can possibly add an opinion. I really like auto-formatting because I can ignore formatting things nicely, knowing it will be fixed. If you don't enforce the format the main codebase, though, you'll get massive, unrelated (whitespace+) changes in every PR.

Note: Whitespace+ since black does things like normalize quote usage, which is more than whitespace and will not pass `git blame -w`.

**Comment by eduardo-rodrigues** [comment]
OK, sounds good.

**Comment by henryiii** [comment]
I'm going to play with a GitHub Action for this, to see if it can be easy to implement that way.

**Comment by HDembinski** [comment]
I haven't used Black, I am not sure what you mean. But generally, I think auto-formatting is a good thing, especially when it can be implemented on the repo-side.

**Comment by henryiii** [comment]
I'm starting to really like [pre-commit](https://pre-commit.com). It's pretty easy to set up, and much better than the home-cooked solution I've used in the past.

The author is working on setting up GitHub actions (he's currently waiting on GitHub support; actions are not allowed to push to a fork even if maintainers have access to push to that fork through the pull request, which is arguably the most important use case for this).

I'll work on this when that gets a bit farther along.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/177.
