### ISSUE TITLE
Data files licenses?

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/particle#190]
We'd like to create a Julia version of this wonderful package and wanted to ask if we could reuse your `data` files. With proper citation of course!

**Comment by eduardo-rodrigues** [comment]
You are certainly welcome to do so. BTW, I will probably have minor updates to them, and probably need to improve a bit the doc on what they provide, so feel free to ask anything unclear.

Glad you like the package :-).

**Comment by tamasgal** [comment]
Thanks for the prompt reply and permission! :)

What do you think about a version number somewhere in the header of the data files? We could then easily compare and also set up a CI on our side to check occasionally for updates.

**Comment by henryiii** [comment]
I'd like to see a link to the Julia package when it's ready, I'm curious to see what it will look like. :)

**Comment by tamasgal** [comment]
Sure! The project has been started ;)

**Comment by eduardo-rodrigues** [comment]
> What do you think about a version number somewhere in the header of the data files? We could then easily compare and also set up a CI on our side to check occasionally for updates.

The CSV files read with `csv` have limitations so having a comment line would need special code for the `csv.dictReader`. As the files will (soon ;-)) be rarely updated I would hope that we can go withing versioning per se. This being said, you could have a check for every major new version?

**Comment by tamasgal** [comment]
I can live with that, sure! I mean I can simply refer to the package version as a whole.

However, I also quickly created a pull request, so feel free to merge it if you think it's a good idea to have comments in the CSV files: https://github.com/scikit-hep/particle/pull/192
