### ISSUE TITLE
Geant4 IDs

### ISSUE THREAD

**Issue by tamasgal** [scikit-hep/particle#206]
Does anyone happen to know where to obtain the Geant4 ID table? I wanted to create a PR which changes the `GEANTID` column to `GEANT3ID` in `conversions.txt` etc. and also adds the `Geant4` codes but I have not found them yet. I also grepped all kinds of particle codes in the Geant4 source, but no luck.

Anyways, I should probably directly contact the Geant4 devs...

**Comment by eduardo-rodrigues** [comment]
In fact Geant4 follows the PDG rules, hence Geant4ID=PDGID. I made a note about this in PR https://github.com/scikit-hep/particle/pull/204 but should update `data/README.rst` to make it clear. Will do.

The latest conversions file, `https://github.com/scikit-hep/particle/blob/master/particle/data/conversions.csv` has been corrected. All is released under 0.8.0.

Let me know if you need anything else … Maybe there are other MC programs relevant to you, such as CORSIKA, which used other ID schemes, and we could add those?

**Comment by tamasgal** [comment]
OK thanks, I personally do not work as often with Geant and now it turned out that we have legacy software which indeed uses Geant3 codes internally, although it has been updated to work with Geant4. That's why I was confused in first place. What a mess :wink: 

Case closed...
