### ISSUE TITLE
B*- has infinite ctau

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#209]
```
(Pdb) p p
<Particle: name="B*-", pdgid=-523, mass=5324.70 ± 0.22 MeV>
(Pdb) p p.ctau
inf
```

**Comment by eduardo-rodrigues** [comment]
Thanks for reporting. There is a flaw in the way that some particles are updated when we have to correct the PDG data with extended data (from the 2008 PDG extended table, which no longer exists). I will fix this soon.

The correct return should be a `None`, for "unknown", as it is for others particles with the same lack of info.

**Comment by eduardo-rodrigues** [comment]
FYI @HDembinski the fix is now available as release 0.8.1 - https://pypi.org/project/Particle/0.8.1/.

**Comment by HDembinski** [comment]
Thanks!

**Comment by HDembinski** [comment]
A bit of context: I am using ctau to discriminate long-lived particles from the others. I would prefer if it was specified that ctau is NaN when it is not available, because it would allow one to write a branch like this:
```
if p.ctau > 1*cm:
    # do long-lived particle branch
else:
    # do short-lived particle branch
```
Of course this works only correctly when you know that some ctau values are NaN. But if this is specified, it allows one to skip the extra check:
```
if p.ctau is not None and p.ctau > 1*cm: ...
```
which is more explicit, but less readable.

**Comment by eduardo-rodrigues** [comment]
Hi @HDembinski, I am coming back (finally) to the package and will try and deal with issues this week … I still had it on my to-do list to reply to your comment above - it was not forgotten.

So, NaNs have been considered. They bring nothing better than `None` for cases of missing info. Moreover, you can't actually do what you mention above, see the following examples:
```
In [1]: float('nan') > 0
Out[1]: False
In [2]: float('nan') < 0
Out[2]: False
In [3]: float('nan') == 0
Out[3]: False
```

In the end the choice of `None` is the best IMO. At least the API is not too bad with this choice.
