### ISSUE TITLE
Nuclei are not handled

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#210]
```
(Pdb) p P.from_pdgid(1000130270)
*** particle.particle.particle.ParticleNotFound: Could not find PDGID 1000130270
```

**Comment by HDembinski** [comment]
This is not a question, it was intended as a bug report.

**Comment by eduardo-rodrigues** [comment]
I have indeed recently added PDG IDs for a bunch of nuclei - what I could find. The known values and conversions are at `https://github.com/scikit-hep/particle/blob/master/particle/data/conversions.csv`. But the particle information comes from the PDG data table, which we improve (already quite a bit), which explains why no nuclei data is available in the `Particle` class. It would not be that trivial to add all the info.

**Comment by HDembinski** [comment]
I am using `particle` to get names for all the particles which occur in a standard pp LHCb simulation, apparently also nuclei are generated in some detector interaction.

**Comment by eduardo-rodrigues** [comment]
In other words, it is not a bug. We already provide more than the PDG. Nothing is impossible but I would need help … My idea of having the conversions was precisely to circumvent the limitations of the PDG table. Often what is needed is only conversion of IDs for MC programs and names.

**Comment by HDembinski** [comment]
If you don't have a table entry for nuclei, I would fall back to a standard solution. You can get the charge and mass approximately from the PDGID, right?

**Comment by eduardo-rodrigues** [comment]
I have recently provided some maps that should help for what I mention below, see for example `EvtGenName2PDGIDBiMap`. Is this not enough for your usecase?

**Comment by HDembinski** [comment]
As name you can set "Nucleus(27, 13)"

**Comment by HDembinski** [comment]
No, because I think that `particle.from_pdgid` should not raise errors as much as it does. It should try harder to return something useful.

**Comment by eduardo-rodrigues** [comment]
The PDGID does not encode anything related to mass. Charge it does, which you can get directly from the `PDGID(...)` ... `Particle` and `PDGID` are different beasts.

**Comment by HDembinski** [comment]
It also encodes that there are 27 nucleons, from that you can compute the mass, approximately.

**Comment by HDembinski** [comment]
You can also fill the charge = 13.

**Comment by eduardo-rodrigues** [comment]
It may be better to discuss viva voce, as there are many things to care about here. For consistency, when you get the `Particle` from the table, you should be able to reply to all questions `Particle` implements. Falling back as you say will open a Pandora box I'm sure. But we can discuss this with time, and with example usecases. In other words, I think you are basically requesting a Particle *creation* on the fly, not a particle from the table, which one cannot get.
Again, we can circumvent, but that's not a 5-minute job, and it needs careful design.

**Comment by HDembinski** [comment]
How it is implemented, does not matter for the user, right? My naive user expectation is that I can do `particle.from_pdgid(...)` and it tries to return something useful. I don't want to be forced to write code like this:
```
try:
   p = particle.from_pdgid(some_pid)
   print(p.name, p.ctau, p.charge)
except ValueError:
   # bummer, pid was nucleus, handle differently...
```
If you cannot fill all the fields of `Particle`, you could return `None` or `nan` where information is missing, as appropriate. This way, at least the queries which make sense still work, like `p.charge`.

**Comment by HDembinski** [comment]
Providing names for all nuclei is also possible, since you know Z, you can look up the name of the element.

**Comment by eduardo-rodrigues** [comment]
> Providing names for all nuclei is also possible, since you know Z, you can look up the name of the element.

That must be possible, sure, though I do not have the info programmatically at hand. Do you know of a mapping somewhere?

**Comment by eduardo-rodrigues** [comment]
> How it is implemented, does not matter for the user, right? My naive user expectation is that I can do particle.from_pdgid(...) and it tries to return something useful. I don't want to be forced to write code like this:
> try:
>    p = particle.from_pdgid(some_pid)
>    print(p.name, p.ctau, p.charge)
> except ValueError:
>    # bummer, pid was nucleus, handle differently...
> 
> If you cannot fill all the fields of Particle, you could return None or nan where information is missing, as appropriate. This way, at least the queries which make sense still work, like p.charge.

Like I said, Hans, "anything" is just about possible. But what you ask is going far beyond the idea of providing a nice interface to the PDG data table. I hope you realise that your suggestion implies info from other sources and a bunch of if statements or try ... Sure that's not going to be more confusing? The source of the info *is* important, in my opinion. I would want to know as a user.

I hope you at least agree that a safe/proper implementation of all this is not a 15-minute job ...

**Comment by eduardo-rodrigues** [comment]
@henryiii, what's your take on this non-trivial extension for basic info on nuclei? We should keep in mind that this hoes far beyond providing an interface to the PDG data table.

**Comment by henryiii** [comment]
We could write a function to generate a list of nuclei based on guesses, then provide that. Then it is explicit (user is okay with guesses), it's clear where the data comes from (guesses), and it doesn't keep us from adding better versions later in the table, and users can select what they want.

```python
Particle.load_table(generate_nuclei(), append=True)
```

Keep in mind that users can add any particles they want. You can make a csv file with your nuclei, and then load it; once you do so, the PDGID lookup will start working. You never need to add if's/try's. (A few utilities to make the tables a bit easier to create might be helpful, though)

**Comment by eduardo-rodrigues** [comment]
Is this suggestion something viable to you, @HDembinski?

**Comment by HDembinski** [comment]
Let me be the voice of the naive user for you :). Maybe your initial goal was to provide a db frontend, but why not go beyond that? The name "particle" does not refer to any database, so I don't see why "particle" should be limited to what is in the DB. I can use "particle" just fine without knowing what kind of DB is there in the background, you are not explicitly loading the DB or ask the user to load the DB. The DB is effectively an implementation detail. I am looking at the library from that point of view. 

And from this point of view, a code like this:
```
for pid in mc_particle_pids:
    if particle.from_pdgid(pid).charge !=0: # I want only charged particles
        # do things
```
should just work for anything that in a standard LHCb simulation file, which apparently contains nuclei. This is certainly true for pPb runs and even true for pp runs. You can get the charge from the PDGID for nuclei, so I think that information should be provided whether there is a DB entry or not. You can also give a name for every nucleus. You cannot fill a lot of the other fields, but that is ok. Maybe you can include another DB in the future to fill those entries. There is the `periodictable` package, for instance.

So, no; I don't think it is a good idea to ask me to load the table when you hide this by default. You need to make up your mind what is an implementation detail and hide those. If it is not an implementation detail, I would make loading the DB explicit, not implicit.

**Comment by HDembinski** [comment]
Mostly, I just think that `particle` should just be as easy and intuitive and convenient to use for people as possible.
