### ISSUE TITLE
Deprecation warning in particle.py

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#226]
Hi, I am getting a deprecation warning in python3.6. I am using particle 0.9.2.
```
/usr/local/Caskroom/miniconda/base/envs/prompt_hadrons/lib/python3.6/site-packages/particle/particle/particle.py:65: DeprecationWarning: The usage of `cmp` is deprecated and will be removed on or after 2021-06-01.  Please use `eq` and `order` instead.
```

**Comment by henryiii** [comment]
https://www.attrs.org/en/stable/changelog.html#id3

We are doing this manually anyway, but we can use order instead and require attrs 19.3+.

**Comment by HDembinski** [comment]
I think you mean 19.2+ right?

**Comment by henryiii** [comment]
Yes, I missed the 19.2 heading. 19.3 was very short...

**Comment by HDembinski** [comment]
Fixed! :D
