### ISSUE TITLE
Redundancy and inconsistency between setup.py and requirements.txt

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#229]
In setup.py, we have:
```
INSTALL_REQUIRES = [
    'enum34>=1.1; python_version<"3.4"',
    'importlib_resources>=1.0; python_version<"3.7"',
    "attrs>=17.4.0",
    "hepunits>=1.1.0",
]
```

In requirements.txt, we have:
```
enum34>=1.1; python_version<"3.4"
importlib_resources>=1.0; python_version<"3.7"
attrs
hepunits
tabulate
```

I propose to read the requirements in setup.py from requirements.txt to enforce consistency between them.

**Comment by HDembinski** [comment]
I would also try to add a unit test to make sure that requirements-dev.txt is a strict superset of requirements.txt.

**Comment by henryiii** [comment]
Why have a requirements.txt at all?

**Comment by HDembinski** [comment]
I don't know :)

**Comment by henryiii** [comment]
I'd add the dev requirements as a extras (`[dev]`) and remove these files, but maybe that's just me.

**Comment by HDembinski** [comment]
https://stackoverflow.com/questions/14399534/reference-requirements-txt-for-the-install-requires-kwarg-in-setuptools-setup-py

**Comment by HDembinski** [comment]
Also relevant but not conclusive:
https://packaging.python.org/discussions/install-requires-vs-requirements/

**Comment by HDembinski** [comment]
I like your solution, @henryiii

**Comment by henryiii** [comment]
The point there in the comments is that install_requires has the minimum requirements to get the package to work. You should view requirements.txt as a package manager guideline - which is not necessarily the same thing, and doesn't often have a reason to sit in your package at all. If you are building a non-installable (no setup.py) package, like an analysis, then requirements.txt would be used to get and pin versions.

So I like getting rid of requirements.txt. We don't have to get rid of the dev one (as we are using it to set up a test environment), but extras_require is a nicer way to to that and can be accessed by users - requirements.txt are not accessible from the wheel 99% of users download via pip, but the extras are.

**Comment by henryiii** [comment]
I can do this in the near future, along with moving the most of the code from setup.py to setup.cfg, if you want.

**Comment by eduardo-rodrigues** [comment]
It's a good move. To be honest I had this in mind since a while but never got to the work - I should have made an issue a while back! Thanks for bringing this up.

**Comment by HDembinski** [comment]
This can closed, I think?
