### ISSUE TITLE
Design issue: tight tool coupling

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#233]
I looked into the `Particle.dump_table` method and saw some worrisome design choices, and so I wanted to write this down. To make it brief, adding convenience features is tempting, but it leads to interface and implementation bloat and one should really think twice about it. As a general rule, instead of calling some external tool inside your own interface, one should instead prepare the data in ones own tool so that the other external tool can easily consume it. This leads to a decoupling between Python packages, more combinatorical options for the user, and reduces interface, implementation, and unittest bloat.

This is a bit abstract, so let me point out what I mean specifically.

`dump_table` calles `tabulate` internally to make nice tables of the Particle data. This is nice, yes, but the same effect could have been obtained by just preparing the table data as a dict in Particle, and let the user pass this data to `tabulate`
```
tabulate(Particle.dump_table2(<options not related to tabulate>), <tabulate options>)
```
It is a really good idea to use `tabulate`, and this package can be recommended in the documentation, shown in examples, tutorials, mentioned in the FAQ. The call is an oneliner, there is barely more to type here than before.

But as the maintainer of Particle you save yourself a lot of work:
*You don't have to add, forward, document, and unittest keywords that change the output of `tabulate`, because the user is calling `tabulate` now and they can look up the options for `tabulate` themselves.*

If there is ever a package `super_tabulate` that is suddenly all hip with the kids, you don't have to do anything, users can just use that instead of `tabulate` (assuming that `super_tabulate` accepts the same input).

For me one of the key ideas of Scikit-HEP as a modular collection of specialized tools is to reduce direct coupling of tools like in `dump_table`, but offer generic and clear interfaces to pass data from these tools. This gives you enormous combinatorial power, and it reduces the implementation, documentation, and unittest load of each individual tool.

The fact that `dump_table` also supports a `filename` keyword to write to a file is just another variant of the same problem. Writing strings to a file is really easy in Python, you don't have to offer a functionality for that. Yes, it allows to quickly dump the output to a file, but it does not scale. What if I want to write it into a pipe instead of a normal file? What if I want to append the table to a file that has already some content? There are many ways to customize the action "write to a file-like object". If you try to support all those options, you need to add so many options to your interface. Or you just don't offer this shortcut. In Python there should be one way to do it. Writing stuff to files means you do `with open(filename, "w") as f: f.write(stuff)`. It is simple for simple things and scales to really complex things. And in Particle you only have to provide `stuff`.

**Comment by HDembinski** [comment]
In other words, we really need to resist the temptation to offer a convenience method for everything. Instead we should document how our tools work well with other packages and how synergies are archived.

**Comment by HDembinski** [comment]
I cannot always cite my sources explicitly, but be assured that this is not my personal opinion. This advice to decouple software components is standard in books about software design and followed by high-quality software projects. I hope the argument is objectively appealing.

**Comment by eduardo-rodrigues** [comment]
Hi @HDembinski and @henryiii, seems this feedback from you got a bit forgotten. I apologise for this!

Two immediate reactions:
- Your feedback is greatly appreciated 👍 !
- I take your good points and thank you for the comprehensive thoughts and explanations.

So you strongly suggest that we drop `Particle.dump_table` and effectively replace this with a method that provides the necessary input for the user to then, say, get the same result with `tabulate`, or use some other way of printing out or even storing to file. Here is a first trial:

```
In [1]: from particle import *

In [2]: from tabulate import tabulate

In [3]: print(Particle.dump_table(exclusive_fields=['pdgid', 'pdg_name'], n_rows=5))  # PRESENT METHOD
  pdgid  pdg_name
-------  ----------
      1  d
     -1  d
      2  u
     -2  u
      3  s

In [4]: query_as_list = Particle.to_list(exclusive_fields=['pdgid', 'pdg_name'], n_rows=5)  # SUGGESTED REPLACEMENT

In [5]: print(tabulate(query_as_list, headers='firstrow'))
  pdgid  pdg_name
-------  ----------
      1  d
     -1  d
      2  u
     -2  u
      3  s

In [6]: query_as_list  # CHECKING THE OUTPUT
Out[6]:
[['pdgid', 'pdg_name'],
 [<PDGID: 1>, 'd'],
 [<PDGID: -1>, 'd'],
 [<PDGID: 2>, 'u'],
 [<PDGID: -2>, 'u'],
 [<PDGID: 3>, 's']]
```

Would that be a viable solution for you? Do you have a better suggestion? Happy with the name?

Note that one could also provide a `Particle.to_dict`, I would imagine.

Let's discuss :-). Thanks a lot.

**Comment by eduardo-rodrigues** [comment]
BTW, the method `Particle.to_dict` would then be trivial and again usable by `tabulate` and others, as seen in this little example:

```
In [9]: to_dict = [dict(zip(query_as_list[0], v)) for v in query_as_list[1:]]  # the one-liner `Particle.to_dict` using `Particle.to_list`

In [10]: print(tabulate(to_dict, headers='keys'))
  pdgid  pdg_name
-------  ----------
      1  d
     -1  d
      2  u
     -2  u
      3  s
```

**Comment by HDembinski** [comment]
Hi Eduardo, yes you on point. I think .to_dict is a fitting interface, especially now that the key order is fixed in Python dicts.

**Comment by eduardo-rodrigues** [comment]
Thanks a lot @HDembinski for the speedy reply. Cool.

**Comment by eduardo-rodrigues** [comment]
In the end I reworded the `to_dict` to a better solution. Done. Thanks again for the feedback and great discussion.

**Comment by eduardo-rodrigues** [comment]
Closed with https://github.com/scikit-hep/particle/pull/261.
