### ISSUE TITLE
Plans for packaging

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#236]
* [ ] Automate releases
* [x] Document dev setup
* [x] Maybe convert to GitHub Actions (still using Azure for coverage)

---
* Check readthedocs & docs (no docs, so nothing to change)

**Comment by eduardo-rodrigues** [comment]
For readthedocs I would very much like to see them appearing under scikit-hep.org/particle, similar to the existing https://scikit-hep.org/pyhf/ and others. It's neat.

**Comment by eduardo-rodrigues** [comment]
So far I'm very happy with Azure pipelines.

**Comment by henryiii** [comment]
> appearing under scikit-hep.org/particle

I actually really don't like that at all. When I type "pyhf.readthedocs.io", since that's how I find every other python package's docs, I get an old version of pyhf! I'd have to learn to type scikit-hep.org/X just for scikit-hep packages, and readthedocs for the rest of the world. I thought the whole point was to use the standards were possible? We can still link to readthedocs from scikit-hep.org, so we really don't seem to gain anything by that. And now we can't add a page named scikit-hep.org/pyhf.

Also I don't think we currently have docs? I thought we did, but there is nothing really in the docs folder.

**Comment by henryiii** [comment]
The problem with Azure is the extra permissions model, the manual GUI release setup I have to do on every package, and the GUI step which seems really hard to skip. GHA has better GUI integration and a much simpler GUI, and can easily trigger on tags. The two systems have the same backend, so converting should be trivial (except for the full binary wheel system, but I have a possible plan for that).
