### ISSUE TITLE
Laziness feature request: `from particle import literals`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#238]
Literals are great and I want to use them a lot!

Currently, I need to import literals like this
`from particle.particle import literals as lp`
For the end user it is not obvious why one has to type the middle `particle`, so this is a bit confusing (I think I understand why you organised it like this, but just saying).

It would be a great convenience if I could just import my literals like this
`from particle import literals as lp`

**Comment by tamasgal** [comment]
That would be a nice first PR 😉

**Comment by henryiii** [comment]
Should it be something like `particle_literals`? There are also PDGID literals, which is why they are structured this way. Though I think particle should be the default/easy one.

**Comment by eduardo-rodrigues** [comment]
Right, we could keep `from particle.pdgid import literals as lid` for `PDGID` literals and make the particle literals available from the top-level import? That's doable.

**Comment by HDembinski** [comment]
That sounds like a good solution.

**Comment by HDembinski** [comment]
Great, if I could I would give another star.
