### ISSUE TITLE
Add missing particles

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#24]
The following particles need to be added:

| PID     | Name            | C  |
|---------|-----------------|----|
|      21 | g               | 0  |
|      25 | H               | 0  |
|    5332 | Omega(b)        | -  |
|   10221 | f(0)(1370)      | 0  |
|   10553 | h(b)(1P)        | 0  |
|   11112 | Delta(1900)     | -  |
|   11212 | Delta(1900)     | 0  |
|   12122 | Delta(1900)     | +  |
|   12222 | Delta(1900)     | ++ |
|   30553 | Upsilon(2)(1D)  | 0  |
|  103316 | Xi(1950)        | -  |
|  103326 | Xi(1950)        | 0  |
|  104122 | Lambda(c)(2625) | +  |
|  104312 | Xi(c)(2815)     | 0  |
|  104314 | Xi(c)(2790)     | 0  |
|  104322 | Xi(c)(2815)     | +  |
|  104324 | Xi(c)(2790)     | +  |
|  203312 | Xi(1690)        | -  |
|  203316 | Xi(2030)        | -  |
|  203322 | Xi(1690)        | 0  |
|  203326 | Xi(2030)        | 0  |
|  203338 | Omega(2250)     | -  |
|  204126 | Lambda(c)(2880) | +  |
| 1000223 | omega(1420)     | 0  |

**Comment by eduardo-rodrigues** [comment]
Better specify above where you see them missing ...
