### ISSUE TITLE
Test the notebooks

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#240]
One could make use of the `papermill` package to extend the tests to the notebooks available. At present there is no 100% guarantee that developments don't break the notebooks.

**Comment by henryiii** [comment]
It's not necessary to use papermill if you just want to execute notebooks in CI, I do that in several other places (like boost-histogram). We should do that here too.

Thanks for reminding me of the name, though; I'd forgotten what it was called, so couldn't find it (I also remembered it was a byproduct from a larger organization, but I forgot which one (nteract).

**Comment by eduardo-rodrigues** [comment]
I do not know of another way. Happy to know you do something along these lines in boost-histogram. The requirement is that we test these notebooks to ensure we break nothing, as for the code.

**Comment by eduardo-rodrigues** [comment]
Does this mean that you will suggest a PR, @henryiii ? Thanks.

**Comment by henryiii** [comment]
I will include it in my next PR, sure.
