### ISSUE TITLE
Querying quark content from Particle is difficult, is there an easier way?

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#264]
Today I wanted to get all particles which have at least one strange quark. I found `Particle.quarks` and so I naively did:

```py
Particle.findall(lambda p: "s" in p.quarks.lower())
```
However, this finds also
```
pi0 (uU-dD)/sqrt(2)
rho(770)0 (uU-dD)/sqrt(2)
a(2)(1320)0 (uU-dD)/sqrt(2)
rho(3)(1690)0 (uU-dD)/sqrt(2)
a(4)(1970)0 (uU-dD)/sqrt(2)
a(0)(1450)0 (uU-dD)/sqrt(2)
b(1)(1235)0 (uU-dD)/sqrt(2)
pi(2)(1670)0 (uU-dD)/sqrt(2)
a(1)(1260)0 (uU-dD)/sqrt(2)
rho(1700)0 (uU-dD)/sqrt(2)
[...]
```
It makes sense to me that `Particle.quarks` returns this, but it makes selecting particles by quark content surprisingly difficult. I would have run into the same issue if I asked for particles with a top quark.

I can work around this, no problem, but I wonder if there is an easier way to select particles by quark content, this seems like a common query.

1. Is there a better way to select by quark content?
2. Wouldn't it make sense to add further attributes to `Particle` to query strangeness, charmness, bottomness, etc?

**Comment by eduardo-rodrigues** [comment]
Hans, isn't `Particle.findall(lambda p: p.pdgid.has_strange)` what you want?

**Comment by eduardo-rodrigues** [comment]
BTW, I get many more particles via your query:
```
>>> len(Particle.findall(lambda p: 's' in p.quarks.lower()))
266
```
That's strange what you are getting.

BTW, that quarks info is one of the extra info we provide, not given via the annual .mcd files from the PDG. Let us know if you spot any place where the info is missing.

**Comment by eduardo-rodrigues** [comment]
Ignore my last comment. I read too quicky. You meant "also get".

**Comment by eduardo-rodrigues** [comment]
I should not that the README has example for queries according to quark content. Maybe that's not visible enough?

**Comment by eduardo-rodrigues** [comment]
Happy for this to be closed, @HDembinski? Seems to me as a solved issue.

**Comment by HDembinski** [comment]
Thank you for the proposed solution. I didn't really study the Readme, so that is on me. I think it is odd though that I cannot query everything from particle, that I have to go to .pdgid. Wouldn't it make more sense if Particle derives from PDGID?

**Comment by eduardo-rodrigues** [comment]
That's a discussion in the other focused issue, whereasthe question here is dealt with within the present scope of the package, hence I'm closing. Let's  continue to discuss the design of the class in https://github.com/scikit-hep/particle/issues/263.
