### ISSUE TITLE
HepPDT Homepage Link

### ISSUE THREAD

**Issue by vvolkl** [scikit-hep/particle#266]
The lcgapp site is down and no longer maintained by CERN. I'm actually having a hard time finding any maintainers for HepPDT -- since it is used by our experiment software and I maintain the spack recipe for it I'm having an interest to not see it get lost. If anybody here is aware of current HepPDT activities please do let me know.

**Comment by eduardo-rodrigues** [comment]
I also have no idea who is maintaining it, unfortunately. Maybe a question for the HSF forum?

BTW, working on updates and improvements in `Particle` I actually noticed that by now the functionality we provide goes beyond what HepPDT provides ... and I also fixed some buglets porting to Python and extending ... Would this Python package suit your needs, by chance? If I'm not mistaken the usage would be for the FCC community?

**Comment by vvolkl** [comment]
> BTW, working on updates and improvements in Particle I actually noticed that by now the functionality we provide goes beyond what HepPDT provides.

Ok, maybe then it's best just to remove the link to HepPDT in the README. 

> Would this Python package suit your needs, by chance?

I think it's great, and I'm definitely using it in my scripts! For FCC, we just provide what is requested, especially what concerns the python/analysis ecosystem, so that's really up to the users.

**Comment by eduardo-rodrigues** [comment]
The mention of HepPDT is there to acknowledge the source from where this package began. It's a fair thing, I reckon. But I will remove the link that is now broken - it wasn't last time I checked. Thanks.

Great to know that some FCC enthusiasts are using `Particle`. More users is always very welcome :-).
