### ISSUE TITLE
ModuleNotFoundError: No module named 'attr'

### ISSUE THREAD

**Issue by b-fontana** [scikit-hep/particle#269]
I tried to use ```particle``` with Python 3.8.5 installed via Miniconda, after installing the package with ```pip install particle```, but got the following:

```bash
Python 3.8.5 (default, Sep  4 2020, 07:30:14) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import particle
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/bruno/.local/lib/python3.8/site-packages/particle/__init__.py", line 20, in <module>
    from .particle import Particle, SpinType, Parity, Charge, Inv, Status
  File "/home/bruno/.local/lib/python3.8/site-packages/particle/particle/__init__.py", line 9, in <module>
    from .particle import Particle
  File "/home/bruno/.local/lib/python3.8/site-packages/particle/particle/particle.py", line 16, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```

**Comment by henryiii** [comment]
Particle should install `attrs` when it installs; it should be very hard to avoid that, in fact. `pip install attrs` should fix your problem, though it doesn't explain why it didn't install it in the first place.

See https://github.com/scikit-hep/particle/blob/bd36ad4e9f158fa05b9f8924f32d5064166e85e8/setup.cfg#L41-L46

You aren't mixing user installs (`-u`) and anaconda, possibly?

**Comment by b-fontana** [comment]
I had indeed already installed ```attrs``` in the system, but Python's ```sys.path``` does not include ```dist-packages``` folders when accessed within a conda environment (I checked this upon running ```python -m site```). As soon as I deactivated the environment the issue was gone, since both ```site-packages``` and ```dist-packages``` are then accessible.
I guess this is ultimately due to mixing ```pip``` with ```conda```, since their installation output directories differ. Will ```particle``` be available in ```conda``` in the foreseeable future? Otherwise, I will eventually have to manually change ```sys.path``` to satisfy all requirements.

**Comment by henryiii** [comment]
Yes, I think we are planning on putting Particle on conda-forge in the near future. What is the output of `which pip`? You might want to verify you are actually using pip from conda. Does `python -m pip` work?

**Comment by b-fontana** [comment]
```which pip``` returns ```~/.local/bin/pip```, and ```python -m pip``` works (but is meaningless without further options). 
For some reason unknown to me, conda's ```base``` environment uses the native version of ```pip```, while a "non-base" environment uses the conda version of ```pip```. Importing ```particle``` in such an environment works as expected.
As a summary, the error observed was due to installing ```particle``` in conda's ```base``` environment, whose ```pip``` command points to the system's native version.

**Comment by henryiii** [comment]
You should not be using `~/.local/bin/pip` in conda - this is why "user" pip installs are so evil. If you have multiple versions of Python (such as conda, venvs, pyenv, etc) then the stuff installed in `.local/` gets picked up by all of them, which is usually only correct for the original one.

Try to always work in environments, or use only one version of a specific Python 3 for everything. I strongly recommend the former. Also, `pip install <package>` will install to your user directory now if the system directory is unwritable, so never install conda as ROOT, etc.

**Comment by henryiii** [comment]
Also, generally never use "pip", but always use "python -m pip". That ensures you never mismatch pip and python. I believe `python -m pip install particle` would have been fine in your case.

**Comment by b-fontana** [comment]
I was anaware of the last option you mentioned, and confirm that running ```python -m pip install particle``` works fine, as it installs the ```attr``` package in the correct directory (```~/.local/lib/<python version>/site-packages```). The command works either in the ```base``` conda environment as well as on a newly created one. Thank you for the answer.
