### ISSUE TITLE
Remove redundant Azure pipelines since we have GitHub actions now

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#300]
The pipelines are redundant at this stage, unless I'm missing something @henryiii?

**Comment by henryiii** [comment]
IIRC I left them for coverage, which I had not converted to GHA yet. I've now set up coverage in a few places, so we probably could base GHA coverage on those. Plumbum has coverage, for example.

**Comment by henryiii** [comment]
Of course, if Azure coverage is broken #299, there's not much lost. :)
