### ISSUE TITLE
Suggestion to deprecate and later remove `Particle.find`

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#313]
Let me start again with my nitpick by saying that I like `particle` very much, I use all the time in my code.

I suggest to deprecate `Particle.find` and to remove it in a future version. It is fully superseded by `Particle.findall` which is the correct interface for a query (well, actually #312 is). `Particle.find` can only return one result, but that is a very special case when the query fundamentally can yield none or several entries. Having such a restricted return type is not a good design and should be a non-starter. The API works around this by raising exceptions whenever the API contract cannot be fulfilled, this works correctly, but it's duck-tape over the more fundamental issue.

Scott Meyers says: "Make interfaces easy to use correctly and hard (or impossible) to use incorrectly". `Particle.find` is very difficult to use correctly (in the sense that you do not get an exception), because a priori, the user cannot know whether the query will yield exactly one result. Frequently, the results will contain zero or more entries, but these states cannot be represented by the method.

If you are not convinced yet, there are three other closely-related design principles which `Particle.find` violates. 

1) Each function/method should do the absolute minimum amount of work that is necessary to respond to the user request.

`find` always first finds all the matches and stores them in a temporary list. But it could stop already when the query found two matches, because then the result is clear, an exception has to be thrown. Also storing everything in a list only to discard that list afterwards is wasting resources. The implemention only needs to store the first match and once a second mathc is found, it can abort by raising an exception. This could be fixed by implementing `finditer` as suggested in #312 and use that internally instead of `findall`, but it would be better to just remove this method.

2) Whenever feasible, fully return the result of some work. In other words, minimize the amount of temporary data that is generated and then thrown away internally in the implementation to respond to some user request.

Functions and methods should be so designed as to return the maximum amount of information for work that has been already done. The idea here is that the work has been performed already so it would be a waste to automatically discard some of that work. Let the user decide what to discard. Even if the user gets more than they intended to get, they may actually find that extra information useful, and if not, it is no problem for them to discard the extra information. If the disposal happens automatically, the extra amount of work is simply wasted.

According to this principle and since `find` first finds all the matches, it should also return all the matches. It already did the work to find all of them, the resources have been used. Designing the API in such a way that then only one result is returned means to automatically discard the rest of the work, without giving the user a choice to look at this extra information. Again, this could be fixed with #312, but `findall` is already the right kind of implementation which returns all results of the query.

3) Only raise exceptions in exceptional situations.

This is an important principle in C++, because exceptions in C++ cost nothing when they are not triggered, but are very costly when they are triggered. This was a deliberate design trade-off to the indented use case of exceptions, namely to signal situations in which the program cannot continue because of some unrecoverable error.

Python is slow whether exceptions are raised or not ;), so the performance argument is not valid, but it is still a good design to use exceptions only in exceptional cases.

How can you avoid raising exceptions in an API? By using return types that can reflect common "error" states and reserve the exception for the truly exceptional circumstance. In C++, one can return a `std::optional` in those cases where it is not clear whether some query can be fulfilled or not. In Python, we return None instead of some object in a similar situation.

`find` can easily fail, since it is rather common that a query does not return exactly one match. So the right design is to chose a return type that can reflect the fact that there can be zero, one, two, or many results, instead of raising exceptions.

**Comment by henryiii** [comment]
I believe `(result,) = finditer/findall`  is identical to `find`. And a "first only" can be implemented as `result = next(iter(finditer))`. I believe this was implemented to support DecayLanguage - if you can uniquely map one result to a given particle, you can use it. If you can map multiple ones, I think we have to take the "simplest" one, that is, the one with the lowest PDGID, so I think we don't really use `find` in DecayLanguage anymore anyway. So I think I'd be fine with removing it. Though it's not all that harmful if someone really wants to keep it.

**Comment by HDembinski** [comment]
> Though it's not all that harmful if someone really wants to keep it.

That is true. The main reason to remove this would be to keep the API minimal and clean.

**Comment by henryiii** [comment]
I think we should probably deprecate it and see if anyone complains. We'll see if @eduardo-rodrigues agrees.

**Comment by mayou36** [comment]
As much as I like the brevity of "find", I agree with the stated arguments and would also tend to deprecate it (or find some useful behavior that matches "find"?). The behavior and the name don't seem well matching each other and it's superseeded by findall

**Comment by eduardo-rodrigues** [comment]
You @HDembinski make good points and I don't quite see how to argue, so I won't ;-). I guess I could only say that it is easy not to implement perfect APIs and code, so take your feedback as fully constructive.

I already made a suggestion for the future of the 2 find methods in https://github.com/scikit-hep/particle/issues/312, which is an alternative to the API changes you propose, so let me only add to that here: I'm also OK with getting rid of one of the methods but would actually stick to `find` in the end since the "all" in `findall` is only needed in the present situation of 2 different behaviours in what is returned by a search. If we mark `findall` as deprecated and break `find` it should be the shortest "path" to what we want eventually, I reckon. Let me know if you agree with all this and we move forward now that a new "major" release is in the pipeline, see https://github.com/scikit-hep/particle/pull/316.

(BTW, any good suggestions for how to implement the deprecation? I seem to recall that you @HDembinski had to write quite some examples for `iminuit`, and I would be happy to follow the examples there.)

**Comment by eduardo-rodrigues** [comment]
> As much as I like the brevity of "find", I agree with the stated arguments and would also tend to deprecate it (or find some useful behavior that matches "find"?). The behavior and the name don't seem well matching each other and it's superseeded by findall

Ah, we were writing at the same time @mayou36 and I did not see this post ;-). So you would actually prefer to stick to `findall` only?

**Comment by henryiii** [comment]
I'd be fine to just use https://deprecated.readthedocs.io/

**Comment by mayou36** [comment]
Hm, true, it's unique the "find", so that should not need to be too expressive.

Is there merit in "findbest" that would only find one (if there are many, it picks the best)?I think practically, user will use `next(find(...))` "blindly" anyway and not checking the alternative found matches.

**Comment by HDembinski** [comment]
@eduardo-rodrigues whether the method you keep is called find or findall, I don't mind much, but I think that findall is a more clear name.

Please do not try to implement "findbest", there is no way to guess what the user wants if there are several matches to a query. As the Zen says "When you face ambiguity, refuse the temptation to guess."

**Comment by mayou36** [comment]
I agree. My suggestion came to mitigate that users may attempt to just take the first one (as there is one example in the readme), so I would not advertise (or rather discourage) the usage of `findall(...)[0]`

If the string is exactly known, there is a `from_string` that should be used.

I also don't mind a lot, but also slightly tend to `findall`, it is more explicitly saying that a container (-like) object is returned while still being short.

Just as a side comment, I would suggest to make sure that the `__str__` still prints out all particles explicitly (for the interactive usecase).

**Comment by eduardo-rodrigues** [comment]
> @eduardo-rodrigues whether the method you keep is called find or findall, I don't mind much, but I think that findall is a more clear name.

Sounds good to me too.

> Please do not try to implement "findbest", there is no way to guess what the user wants if there are several matches to a query. As the Zen says "When you face ambiguity, refuse the temptation to guess."

I had no plans to go with `findbest` ;-). The argument from @henryiii on naming similarly to `re` is fair IMO.

**Comment by eduardo-rodrigues** [comment]
> Just as a side comment, I would suggest to make sure that the __str__ still prints out all particles explicitly (for the interactive usecase).

You mean `Particle.__str__`, @mayou36? No intention to touch that.

**Comment by henryiii** [comment]
I think he meant the repr for the generator?

**Comment by mayou36** [comment]
> I think he meant the repr for the generator?

Yes, that the return value of `findall` has a nice string representation. That would be useful in interactive searches in ipython and co. Programmatically, a generator seems the Python way to go, but for visualization in interactive searches it could be useful to see all the particles at once directly.

**Comment by eduardo-rodrigues** [comment]
OK, so I deprecated `Particle.find` in https://github.com/scikit-hep/particle/pull/318 and tagged you all. That closes this one "issue" that is very scoped/well-defined. The rest of the discussions should be discussed on https://github.com/scikit-hep/particle/issues/313 to have it all in one place. I would be tempted to release 0.16 with this one new PR and then work on the breaking changes for a future 0.17.

Thanks for the constructive discussions towards a better package, BTW.
