### ISSUE TITLE
Add documentation on the new `particle.lhcb` experiment-specific module

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#365]
Hi @admorris, making this a task so that we do not forget. I'm happy to work on this soon ...

Just to make sure - is there a need to have the module supporting Python 2 or the Python-3 version on master since yesterday is enough? That would be preferable, of course, since requiring less maintenance/branching.

**Comment by eduardo-rodrigues** [comment]
(BTW, drop a line and assign yourself to the task if you are going to work on it, so that we do not duplicate. I will do the same.)

**Comment by admorris** [comment]
I can't think of a compelling use-case to motivate python 2 support

**Comment by eduardo-rodrigues** [comment]
> I can't think of a compelling use-case to motivate python 2 support

My either ;-). Cool, makes life easier.
