### ISSUE TITLE
improve from_search_list for real-valued particle properties and improve documentation

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#38]
`Particle.from_search_list` is better documented in the README than in the pydoc. In the README it says I can select particles by keywords, name, charge, status, etc. The system works fine for name, charge, and a few other discrete properties, but doesn't work well for masses. It is also not documented which argument type is expected in the docs.

For real-valued properties like the mass and life-time, I would like to be able to write something like this
```
from particle.search_variables import mass
Particle.from_search_list(mass > 100*MeV)
```
`mass` here is an instance of a new class SearchVariable, which has comparison operators defined in a special way that stores the comparison argument and the type of comparison and then acts as an unary predicate. Inside the `from_search_list` function, one would do (not actual code):
```
accept = []
for particle in table:
   if mass(particle.mass):
     accept.append(particle)
```

**Comment by henryiii** [comment]
I would do it slightly differently to be more pythonic:

```python
Particle.from_search_list(mass = lambda x: x > 100*MeV)
```

Which would have a helper, similar to lambdas in boost::

```python
from particle import x # Name TBD
Particle.from_search_list(mass = x > 100*MeV)
```

But, still a great idea.

**Comment by HDembinski** [comment]
Ok, very good! :) More pythonic syntax is appreciated.
I am also ok with just passing a lambda.
```
Particle.from_search_list(lambda x: x.mass > 100 * MeV)
```
Selection by predicate is pretty clear Pythonic syntax.

**Comment by eduardo-rodrigues** [comment]
Closed with https://github.com/scikit-hep/particle/pull/47.
