### ISSUE TITLE
Include the tests in the pypi tarball please

### ISSUE THREAD

**Issue by doronbehar** [scikit-hep/particle#386]
I'd like to add this package to NixOS, and I noticed you don't include the tests in the pypi tarball. I also noticed that I can't use the GitHub tarball since it doesn't contain a `version.py` file, and also `setuptools-scm` can't detect the version when I use a GitHub tarball. NixOS also has an issue with using git checkouts (see https://github.com/NixOS/nixpkgs/pull/4752) that would have helped `setuptools-scm`.

Thanks in advance.

**Comment by eduardo-rodrigues** [comment]
Thanks for the interest. Before anything, what is the use-case to have the tests in the PyPI tarball? I would assume that anyone wanting th run tests would be developing and hence cloning the package.

**Comment by doronbehar** [comment]
> Thanks for the interest. Before anything, what is the use-case to have the tests in the PyPI tarball? I would assume that anyone wanting th run tests would be developing and hence cloning the package.

On NixOS it's considered good practice to run tests during the build. Indeed it's great because it helps us find problems before packages reach the users, by making the build of them fail.

**Comment by henryiii** [comment]
Tests should be in the SDist to help downstream packagers (including Conda-forge). So we don’t have to repeat this on every repo, we should add it to the developer guidelines. https://github.com/scikit-hep/iminuit/pull/569

**Comment by eduardo-rodrigues** [comment]
Happy for PR https://github.com/scikit-hep/particle/pull/387 to close this? Files `version.py` are now created on the file as in the other org packages.

**Comment by doronbehar** [comment]
Yes I think this should be fine now if I'll use the pypi tarball, the `version.py` file is included there. I'll open an issue if there's a problem in the next release.

**Comment by eduardo-rodrigues** [comment]
Perfect. Do not hesitate to get back to us.

I will make a release as soon as out of a meeting.

**Comment by eduardo-rodrigues** [comment]
FYI version 0.20.1 is out on PyPI (https://pypi.org/project/particle/0.20.1/).
