### ISSUE TITLE
add life-time to particle properties

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#39]
I cannot look up the life-time of particles, the information is missing. Life-time would very useful in LHCb and elsewhere for the definition of final state particles. A final state particle is one with a given minimum lifetime.

**Comment by eduardo-rodrigues** [comment]
Yep, 100% in agreement.

You were too fast with feedback … ;-)
Joke aside: thanks for the ping. I really need to re-organise the scikit-hep package and in particular take the 2 relevant functions (and the units module) out, see https://github.com/scikit-hep/scikit-hep/blob/master/skhep/math/kinematics.py.

I will work on this asap.

**Comment by eduardo-rodrigues** [comment]
I started on this front and will be committing various things, see the new package https://github.com/scikit-hep/hepunits.

**Comment by eduardo-rodrigues** [comment]
Done with https://github.com/scikit-hep/particle/pull/46.
