### ISSUE TITLE
Allow lookup for decays and branching ratios

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#40]
`particletools` from Anatoli allows the user to look up particle decays and their branching ratios, which is very nice. Implementing this would require a different data source, a hierarchical data base. The current tabular format of the mcd and csv data tables cannot represent a variable number of branching ratios per particle.

`particletools` uses XML for that purpose, which works, but I would prefer yaml if the data base should be human readable. Another alternative is to code the data base directly in form of Python primitives, using dicts and list literals. It can be easily generated by a script and then "serialized" into a literal using `repr`.

**Comment by henryiii** [comment]
I believe this is the scope of DecayLanguage, specifically in its upcoming ability to read from DecFiles.

**Comment by HDembinski** [comment]
Why is `DecayLanguage`  a separate package? I think it should be part of particle. What is the reasoning behind this decision?

**Comment by eduardo-rodrigues** [comment]
We actually started with DecayLanguage. It needs some developments there, but the idea is for it to be able to do the following:
* Read decay files such as DECAY.DEC, user .DEC files, and a composition of those.
* Read AmpGen files.
* And other goodies.

In other words, DecayLanguage is meant to deal with various forms of inputs and outputs coding particle decays. That's specific enough to have it in one place. We then realised that particle data and PDG IDs are a different topic, worth having separate - having modularity in mind. This one package can be useful to many more people not caring at all about the huge DECAY.DEC file we have in LHCb, for example.

In the end it does make sense to have both particle and DecayLanguage. That's no problem for a user wanting/needing both. It's just a matter of having 2 kinds of import statements.

I hope you understand our logic. I'm closing this. Feel free to reopen if you need more argumentation :-).

P.S.: You comment on having a YAML file is an interesting one to have in mind.
