### ISSUE TITLE
Add tests for DecayLanguage particles

### ISSUE THREAD

**Issue by henryiii** [scikit-hep/particle#41]
The particles used by DecayLauage should be tested. This would require two tests:

- [x] One that reads in AmpGen style names and makes sure they all convert correctly to Particles.
- [x] One that reads in DecFile style names and makes sure they all convert correctly to Particles.

In both cases, the initial input to the mark.parameterize should be a dump from DecayLanguage of all names detected.

**Comment by eduardo-rodrigues** [comment]
FYI, @henryiii, I started addressing this task in https://github.com/scikit-hep/particle/pull/80.

**Comment by eduardo-rodrigues** [comment]
The search of particles given a DecFile style of name requires some work on the regex. I tried playing a bit and it is not trivial for the regex (`getrec` in `particle.regex` submodule) to properly parse and match all particles, for example the following set
```
anti-K*0
anti-nu_mu
Lambda_b0
Lambda_c+
phi
chi_c0
chi_b1(2P)
```
(Name examples taken from https://github.com/scikit-hep/decaylanguage/blob/master/decaylanguage/data/DECAY_LHCB.DEC.)

**Comment by eduardo-rodrigues** [comment]
Dealt with via https://github.com/scikit-hep/particle/pull/101.
