### ISSUE TITLE
Issue publishing

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#436]
See https://github.com/scikit-hep/particle/actions/runs/3419905571:

![image](https://user-images.githubusercontent.com/5013581/200587058-3956f7e2-12ea-495c-a77c-5f594a49dc9e.png)

@henryiii, have you seen this before? I don't think this is the reason for the latest tag 0.21.0 not being published, though. Am looking ...

**Comment by henryiii** [comment]
Those are just warnings. For some reason, GHA doesn't seem to always trigger on publish. I think if we republish it might work.

**Comment by henryiii** [comment]
I copied the release, deleted it, then rereleased it (on the same tag). And the CI triggered. Something is off with with GHA's release triggering.

**Comment by eduardo-rodrigues** [comment]
Ah, I did not realise that "feature". Let me retrigger, see https://github.com/scikit-hep/particle/actions/runs/3419905571 ...

**Comment by eduardo-rodrigues** [comment]
Cool 👍!

I do not quite understand what you did at https://github.com/scikit-hep/particle/releases but that did it. Great, can tick this off and move with other work :-). Thanks a lot.
