### ISSUE TITLE
Confusing `is_quarkonium` in Readme

### ISSUE THREAD

**Issue by APN-Pucky** [scikit-hep/particle#476]
From wikipedia: Quarkonium is a [flavorless](https://en.wikipedia.org/wiki/Flavor_(physics)) [meson](https://en.wikipedia.org/wiki/Meson) whose constituents are a heavy [quark](https://en.wikipedia.org/wiki/Quark) and its own [antiquark](https://en.wikipedia.org/wiki/Antiquark) [1].

But lambdas from the readme are:
```
>>> from particle.pdgid import is_meson, three_charge, has_charm, has_bottom, has_top
>>> is_heavy_flavor = lambda x: has_charm(x) or has_bottom(x) or has_top(x)
>>> is_quarkonium = lambda x: is_meson(x) and three_charge(x)==0 and is_heavy_flavor(x)
>>> is_quarkonium(421)
True
```
Do you have a different definition of a quarkonium? since:
```
>>> Particle.from_pdgid(421)
<Particle: name="D0", pdgid=421, mass=1864.84 ± 0.05 MeV>
>>> p=_
>>> p.quarks
'cU'
```

[1] https://en.wikipedia.org/wiki/Quarkonium

**Comment by APN-Pucky** [comment]
I would rather consider these quarkonia:
```
>>> f=Particle.finditer(lambda p: len(p.quarks)==2 and p.quarks[0] == p.quarks[1].swapcase())
>>> for p in f:
...     print(p.pdgid)
... 
<PDGID: 441>
<PDGID: 443>
<PDGID: 445>
<PDGID: 553>
<PDGID: 555>
<PDGID: 10441>
<PDGID: 10443>
<PDGID: 10551>
<PDGID: 10553>
<PDGID: 20443>
<PDGID: 20553>
<PDGID: 20555>
<PDGID: 30443>
<PDGID: 100441>
<PDGID: 100443>
<PDGID: 100445>
<PDGID: 100553>
<PDGID: 100555>
<PDGID: 110551>
<PDGID: 120553>
<PDGID: 200553>
<PDGID: 300553>
<PDGID: 9000443>
<PDGID: 9000553>
<PDGID: 9010443>
<PDGID: 9010553>
```

**Comment by eduardo-rodrigues** [comment]
Thank you @APN-Pucky for reporting. Seems indeed fishy. It could be that we introduced a couple of hints in code that are not totally to the point. I will look into this next week ...

I do remember adding the property `is_unflavoured_meson` to `Particle` sometime in the past.

Yes your list about seems the right quarkonium. I hope those at least give True with is_quarkonium. To be checked and tests enhanced to be maniac ;-).

BTW, feel free to contribute to the package. It is always welcome. (Let me know if you start on something to avoid any duplication of work.)

Back soon.

**Comment by APN-Pucky** [comment]
Yes, your `is_unflavoured_meson` uses `is_self_conjugate` which works too. Thanks.
