### ISSUE TITLE
Particle fails in Travis

### ISSUE THREAD

**Issue by HDembinski** [scikit-hep/particle#55]
I am installing `particle` as part of my `pyhepmc` requirements for unit tests on travis. It installs and imports fine, but when I try to query the Particle class in my code, I get this error:
```
_____________________ ERROR collecting tests/test_view.py ______________________
../../../virtualenv/python3.6.3/lib/python3.6/site-packages/importlib_resources/_py3.py:120: in open_text
    return open(full_path, mode='r', encoding=encoding, errors=errors)
E   FileNotFoundError: [Errno 2] No such file or directory: '/home/travis/virtualenv/python3.6.3/lib/python3.6/site-packages/particle/data/particle2018.csv'
```
An analog error appears for Python2.7. This doesn't happen on my developer machine, only on Travis. Perhaps it has to do with the virtualenv?

**Comment by eduardo-rodrigues** [comment]
FYI, @HDembinski, release 0.2.2 is deployed. Let me know if all goes fine for you now. Thanks.

**Comment by HDembinski** [comment]
Will do.

**Comment by HDembinski** [comment]
works now, thank you!
