### ISSUE TITLE
Particle.radius property

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#71]
It is not clear what this "obscure" property is for, nor what it returns. Documentation needs to be added, providing information on what this PDG data is, and a a reference to details in the PDG.

**Comment by eduardo-rodrigues** [comment]
Similar question for the `Particle.spin_type` property:

it is not clear where this property is taken from. From the PDG? Info should be added on where the definitions of `Particle.spin_type` and `SpinType` enum are taken from.

**Comment by tevans1260** [comment]
The particle radius is a rather hand-wavey number that is used to regulate the behavior of amplitudes at large momentum transfers, based on the classical Q.M arguments in "Theoretical Nuclear Physics" from Blatt and Weisskopf. IMHO this probably shouldn't be included in the basic PDG properties of a particle, as it isn't really a fundamental parameter and isn't really measured for different particles. It's normally arbitrarily set to be between 1 and 2 GeV for light resonances and between 3 and 5 GeV for charm/beauty.

**Comment by eduardo-rodrigues** [comment]
Thanks a lot for the insight, @tevans1260! What about the spin_type and the related enum, see https://github.com/scikit-hep/particle/blob/master/particle/particle/particle.py#L304 and https://github.com/scikit-hep/particle/blob/master/particle/particle/enums.py#L11?

**Comment by eduardo-rodrigues** [comment]
@henryiii, ok with removing the `Particle.radius` property, then? This makes complete sense to me as not a general PDG particle property.

**Comment by henryiii** [comment]
We can, but let's make sure we don't set slots (it's great for developing, but users might want to add arbitrary information). Also, in response to something else somewhere, particle instances are completely editable. If users want to change the mass, etc, they can.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/85.
