### ISSUE TITLE
Better handling of Particle.empty()

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#82]
The method Particle.empty() is rather special given that, strictly speaking the PDGID=0 defined in it is not a valid ID. The method may be handy, though, so better have a handling of this "special particle" in an appropriate way. In other words, there should be no exceptions thrown when calling the class properties. This is not quite yet the case, hence this issue.

**Comment by eduardo-rodrigues** [comment]
In fact, @henryiii, what's the use-case that made you create this method? No `Particle` property is set-able, after all. I would be tempted to simply remove it.

**Comment by henryiii** [comment]
All particle properties are settable. But the point of this was to make an empty particle to indicate a failure or missing particle.

**Comment by eduardo-rodrigues** [comment]
I've just tried again: some properties are settable, others such as charge and name aren't.

Then a better action would be to make settable what makes sense, and keep the "empty" particle for sitations as you mention. Fine by me.

**Comment by henryiii** [comment]
Generated properties are not settable, but some of them maybe could be. Charge is automatic based on PID, for example, so can't be set. Name is also derived.

**Comment by henryiii** [comment]
(Everything in the constructor is settable later)

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/94.
