### ISSUE TITLE
Organisation of tests of Enums

### ISSUE THREAD

**Issue by eduardo-rodrigues** [scikit-hep/particle#88]
Suggest to remove the tests of Enums (`particle.enums` submodule) from `test_particle.py` to a new file `test_enums.py`.

This is pure organisation. Nothing else.

**Comment by henryiii** [comment]
👍

**Comment by eduardo-rodrigues** [comment]
Addressed with PR https://github.com/scikit-hep/particle/pull/89.

**Comment by eduardo-rodrigues** [comment]
Closed via https://github.com/scikit-hep/particle/pull/89.
